title: Banner
label: Banner
order: 39
status: wip
hidden: false
collate: true
meta:
  dependencies:
    stylesheets:
      - /components/headline/headline.css
      - /components/button/button.css
      - /components/colors/colors.css
      - /components/background/background.css
      - /components/blockquote/blockquote.css
    scripts:
      - /components/video/video.js
      - /assets/js/click-a11y.js
context:
  banner_type: image
  banner_size: large
  banner_content:
  banner_image: 'https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/pano.jpg'
  banner_vertical_alignment: banner--vertical-center
  banner_horizontal_alignment: banner--horizontal-center
  banner_pre_title: University of Iowa
  banner_title: 'Living on Campus'
  banner_text: '<p>A member of the <a href="/">Association</a> of American Universities since 1909 and the Big Ten Conference<br /> since 1899, the University of Iowa is home to one of the most acclaimed academic medical centers<br /> in the country, as well as globally recognized leadership in the study and craft of writing.</p>'
  banner_links:
    - link_title: View Story
      link_url: https://uiowa.edu/
  banner_link_classes: bttn bttn--primary bttn--caps
  banner_aria: desc-a-card
  banner_overlay:  banner--gradient-bottom banner--gradient-dark
  banner_title_classes: 'headline--uppercase headline headline--negative headline--large'
  banner_classes: banner--stacked
variants:
  - name: default
    label: Large, content centered
    hidden: false
    context:
      banner_title_classes: 'headline--serif headline headline--negative headline--large'
  - name: no_button_linked
    label: Large, content centered, no button Linked
    hidden: true
    context:
      banner_links:
        - link_url: https://uiowa.edu/
      banner_text: '<p>Every Hawkeye has a role to play in <a href="https://coronavirus.uiowa.edu">preventing</a> the spread of COVID-19.<br />
                        Find out what Iowa’s doing—and what you can do—to make your return to campus safer.</p>'
  - name: button_row
    label: Button Row
    hidden: true
    context:
      banner_links:
        - link_title: 'Apply'
          link_url: 'https://google.com'
        - link_title: 'Request Information'
          link_url: 'https://example.com'
        - link_title: 'Visit'
          link_url: 'https://example.com'
      banner_link_classes: bttn bttn--primary bttn--caps
  - name: Video
    label: Large, content left aligned, Video, Paused
    hidden: true
    context:
      banner_vertical_alignment: banner--vertical-bottom
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'Living on Campus'
      banner_type: video
      banner_image:
      banner_video: 'https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2020-12/homepage-loop.mp4'
      banner_video_autoplay: true
  - name: multiple
    label: Multiple, Large, content centered, Video
    hidden: true
    context:
      banner_vertical_alignment: banner--vertical-bottom
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'Living on Campus'
      banner_type: video
      banner_image:
      banner_video: 'https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2020-12/homepage-loop.mp4'
  - name: large_centered_left_banner
    label: Large centered left banner
    hidden: false
    context:
      banner_title_classes: 'headline--serif headline headline--highlight headline--large'
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
  - name: large_lower_left_banner
    label: Large lower left banner
    hidden: false
    context:
      banner_content:
      banner_vertical_alignment: banner--vertical-bottom
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--negative headline--large'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
  - name: large_lower_left_highlighted_banner_uppercase
    label: Large lower left highlighted banner uppercase
    hidden: false
    context:
      banner_vertical_alignment: banner--vertical-bottom
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--uppercase headline headline--highlight headline--large'
  - name: large lower_centered_highlighted_banner
    label: Large lower centered highlighted banner
    hidden: false
    context:
      banner_vertical_alignment: banner--vertical-bottom
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--highlight headline--large'
  - name: medium_centered_left_banner
    label: Medium centered left banner
    hidden: false
    context:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_size: medium
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--negative headline--medium'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
  - name: medium_centered_left_banner_reversed
    label: Medium centered left banner reversed
    hidden: false
    context:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_size: medium
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--negative headline--medium'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
  - name: medium_caps_centered_left_banner
    label: Medium centered left banner uppercase
    hidden: false
    context:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_size: medium
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--uppercase headline headline--negative headline--medium'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
  - name: medium_caps_centered_left_banner_reversed
    label: Medium centered left banner reversed uppercase
    hidden: false
    context:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_size: medium
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--uppercase headline headline--negative headline--medium'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
  - name: medium_centered_banner
    label: Medium, content centered
    context:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_size: medium
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--negative headline--medium'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
  - name: medium_lower_left_banner
    label: Medium lower left banner
    hidden: false
    context:
      banner_vertical_alignment: banner--vertical-bottom
      banner_horizontal_alignment: banner--horizontal-left
      banner_size: medium
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--negative headline--medium'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
  - name: medium_centered_left_bg_color_banner
    label: Medium centered left w/ background pattern banner
    hidden: false
    context:
      banner_size: medium
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--negative headline--medium'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
      banner_classes: bg--black--pattern--brain
  - name: medium_centered_left_bg_color_reversed
    label: Medium centered left w/ background pattern reversed banner
    hidden: false
    context:
      banner_size: medium
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--medium'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
      banner_classes: bg--gold--pattern--brain
  - name: medium_centered_left_bg_color_gold
    label: Medium, content left-aligned, centered vertically w/ gold background pattern
    hidden: false
    context:
      banner_size: medium
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--medium'
      banner_classes: bg--gold--pattern--brain
  - name: small_centered_left_banner
    label: Small centered left banner
    hidden: false
    context:
      banner_size: small
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--negative headline--small'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
  - name: small_centered_banner
    label: Small, content centered
    context:
      banner_size: small
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--negative headline--small'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
  - name: small_caps_centered_left_banner
    label: Small centered left banner uppercase
    hidden: false
    context:
      banner_size: small
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--uppercase headline headline--negative headline--small'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
  - name: small_caps_centered_banner
    label: Small, content centered uppercase
    hidden: false
    context:
      banner_size: small
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--uppercase headline headline--negative headline--small'
      banner_links:
        - link_classes: bttn bttn--primary bttn--caps
  - name: small_centered_bg_color_banner
    label: Small, content centered w/ black background pattern
    hidden: true
    context:
      banner_size: small
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--highlight headline--small'
      banner_classes: bg--black--pattern--brain
  - name: small_centered_bg_color_reversed_banner
    label: Small centered w/ pattern reversed banner
    hidden: false
    context:
      banner_size: small
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--serif headline headline--highlight headline--small'
      banner_classes: bg--gold--pattern--brain
  - name: small_caps_centered_bg_color_banner
    label: Small, content centered w/ black background pattern uppercase
    hidden: false
    context:
      banner_size: small
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'Living on Campus'
      banner_title_classes: 'headline--uppercase headline headline--highlight headline--small'
      banner_classes: bg--black--pattern--brain
  - name: small_caps_centered_bg_color_reversed_banner
    label: Small centered w/ pattern reversed banner uppercase
    hidden: false
    context:
      banner_size: small
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'Living on Campus'
      banner_overlay:
      banner_title_classes: 'headline--uppercase headline headline--small'
      banner_classes: bg--gold--pattern--brain
  - name: small_black
    label: Small w/ black background
    hidden: false
    context:
      banner_size: small
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'Living on Campus'
      banner_overlay:
      banner_title_classes: 'headline--serif headline--negative headline headline--small'
      banner_classes: bg--black
  - name: small_gray
    label: Small w/gray background
    hidden: false
    context:
      banner_size: small
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'Living on Campus'
      banner_overlay:
      banner_title_classes: 'headline headline--negative headline--uppercase headline--large default'
      banner_classes: bg--gray
