title: Paragraph
status: wip
order: 0
collated: false
meta:
  dependencies:
    stylesheets:
      - /components/headline/headline.css
      - /components/background/background.css
      - /components/typography/lists/lists.css
context:
    test: test
