title: Menu Top
hidden: true
order: 4
status: wip
context:
    menu_classes: menu--top nav
    menu_top_nav:
      title: Top Menu
      title_classes: element-invisible
      links:
      - menu_top_text: Apply
        menu_top_classes:
      - menu_top_text: Visit
        menu_top_classes:
      - menu_top_text: Request Info
        menu_top_classes:

variants:
  - name: default
    label: Menu Top Links
    hidden: false
  - name: reversed
    label: Menu Top Links Reversed
    hidden: true
    context:
        menu_classes: menu--group menu--reversed
  - name: department
    label: Menu Top Links Department
    hidden: true
    context:
        menu_classes: menu--top nav
        menu_top_nav:
          links:
          - menu_top_text: Careers
            menu_top_classes:
          - menu_top_text: Alumni
            menu_top_classes:

  - name: links
    label: Links
    hidden: true
