version: 2
updates:
- package-ecosystem: npm
  pull-request-branch-name:
    separator: "-"
  directory: "/"
  schedule:
    interval: monthly
    time: "14:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@frctl/mandelbrot"
    versions:
    - 1.7.0
    - 1.8.1
    - 1.8.2
  - dependency-name: "@frctl/fractal"
    versions:
    - 1.5.2
    - 1.5.4
    - 1.5.5
  - dependency-name: "@frctl/twig"
    versions:
    - 1.2.0
