version: 2
updates:
- package-ecosystem: npm
  pull-request-branch-name:
    separator: "-"
  directory: "/"
  schedule:
    interval: monthly
    time: "14:00"
    timezone: America/Chicago
  open-pull-requests-limit: 10
