title: Aerial Block
name: Aerial
order: 99
status: wip
collate: false
meta:
  dependencies:
    stylesheets:
      - /components/headline/headline.css
      - /components/highlight/highlight.css
      - /components/button/button.css
      - /components/colors/colors.css
variants:
  - name: default
    hidden: false
    context:
      aerial_title: 'Welcome Home'
      aerial_image: '../../assets/images/viewbook/sections/12.jpg'
      grid_title_1: 'World-class hospital'
      grid_sub_1: ' A nationally ranked, comprehensive medical center is just a short walk away.'
      grid_title_2: 'Best college town'
      grid_sub_2: 'Named the #1 Best College Town by reviews.org, Iowa City seamlessly blends a vibrant downtown with the heart of campus.'
      grid_title_3: 'Easy to get around'
      grid_sub_3: ' Whether you like to walk, bike, or take the free bus system, residence halls are closely located to the center of campus and downtown Iowa City.'
      grid_title_4: 'Big ten athletics'
      grid_sub_4: 'Seating nearly 70,000, Kinnick Stadium is home to Hawkeye Football, just one of the 24 NCAA teams at Iowa.'
