label: Logo
order: 0
hidden: true
collated: false
context:
    logo_fallback_path: ../../assets/images/uiowa-primary.png
    path: https://www.uiowa.edu

variants:
  - name: default
    label: Tab
    hidden: false
    context:
      logo_classes: 'logo--tab'
  - name: base
    label: Block IOWA
    hidden: true
