title: Headline
order: 10
status: wip
hidden: false
collated: true
variants:
  - name: default
    label: Headline
    hidden: true
    context:
        heading_level: h2
        heading_class:
        heading_url:
        heading_prefix: '$'
        heading: 'Bold Headline Here'
        heading_suffix: '%'
        heading_aria: test
  - name: Bold Headline Caps
    hidden: false
    context:
      heading_level: h2
      heading: Bold Headline Antonio
      heading_class: bold-headline bold-headline--caps
  - name: Bold Headline Antonio with Underline
    hidden: false
    context:
      heading_level: h2
      heading: Bold Headline Antonio Underlined
      heading_class: bold-headline bold-headline--underline bold-headline--caps
  - name: Bold Headline Serif
    hidden: false
    context:
      heading_level: h2
      heading: Bold Headline Zilla Slab
      heading_class: bold-headline bold-headline--serif
  - name: Bold Headline Zilla with Underline
    hidden: false
    context:
      heading_level: h2
      heading: Bold Headline Zilla Slab Underlined
      heading_class: bold-headline bold-headline--serif bold-headline--underline
  - name: Bold Headline Zilla with Highlight
    hidden: false
    context:
      heading_level: h2
      heading: Bold Headline Zilla Slab Highlighted
      heading_class: bold-headline bold-headline--serif bold-headline--highlight


