title: Headline
order: 10
status: wip
hidden: false
collated: true
variants:
  - name: default
    label: Headline
    hidden: true
    context:
        heading_level: h2
        heading_class:
        heading_url:
        heading_prefix: '$'
        heading: 'Bold Headline Here'
        heading_suffix: '%'
        heading_aria: test
  - name: Headline Antonio with Underline
    hidden: false
    context:
      heading_level: h2
      heading: Headline Antonio Underline
      heading_class: bold-headline bold-headline--underline bold-headline--caps
  - name: Headline Caps
    hidden: false
    context:
      heading_level: h2
      heading: Headline Antonio
      heading_class: bold-headline bold-headline--caps
  - name: Headline Antonio with Highlight
    hidden: false
    context:
      heading_level: h2
      heading: Headline Antonio Highlighted
      heading_class: bold-headline bold-headline--underline bold-headline--caps bold-headline--highlight
  - name: Bold Headline Serif
    hidden: false
    context:
      heading_level: h2
      heading: Headline Zilla Slab
      heading_class: bold-headline bold-headline--serif
  - name: Headline Zilla with Underline
    hidden: false
    context:
      heading_level: h2
      heading: Headline Zilla Slab Underlined
      heading_class: bold-headline bold-headline--serif bold-headline--underline
  - name: Headline Zilla with Highlight
    hidden: false
    context:
      heading_level: h2
      heading: Headline Zilla Slab Highlighted
      heading_class: bold-headline bold-headline--serif bold-headline--highlight


