title: Card
status: wip
order: 3
hidden: false
context:
  card_title: Dedicated to having an impact on human health
  card_link_title: View Story
  card_link_url: https://uiowa.edu/
  card_image: ../../images/feature1.jpg
  card_content: <p>Molecular <a href="https://hr.uiowa.edu">medicine PhD</a> student Jordan Kohlmeyer is researching new therapies for malignant peripheral nerve sheath tumors, which are deadly, resistant to drug therapies, and often unable to be operated upon due to their location.</p>
  card_date: June 14, 1984
  card_author: By Lee Hermiston
  card_aria: desc-a-card
display:
  max-width: 500px
variants:
  - name: default
    label: Vertical
  - name: no_title
    label: Vertical w/o title
    context:
      card_title: ''
  - name: no_link
    label: Vertical w/o link
    context:
      card_link_title: ''
      card_link_url: ''
  - name: no_title_or_link_text
    label: Vertical linked via image
    context:
      card_title: ''
      card_author: ''
      card_link_title: ''
  - name: no_image
    label: Vertical w/o image
    context:
      card_image: ''
  - name: enclosed
    label: Enclosed
    context:
      card_classes: 'card--enclosed'
  - name: horizontal
    label: Horizontal
    context:
      card_title: Getting to know Iowa's fall 2018 graduates
      card_image: ../../images/feature1.jpg
      card_classes: 'card--horizontal'
      card_text: <p>Applications can be submitted via Iowa’s web application portal, the Common Application, and Coalition App. Once submitted, <a href="/">you</a> can track the status of your application through MyUI, a one-stop resource for current and prospective Iowa students.</p>
      card_date: June 14, 1984
      card_author: By the Office of Strategic Communication
    display:
      max-width: 1200px
  - name: row
    label: Collection
    context:
      row:
        items:
          - card_title: Dedicated to having an impact on human health
            card_link_title: View Story
            card_link_url: https://uiowa.edu/
            card_image: ../../images/feature1.jpg
            card_text: <p>Molecular <a href="https://hr.uiowa.edu">medicine PhD</a> student Jordan Kohlmeyer is researching new therapies for malignant peripheral nerve sheath tumors, which are deadly, resistant to drug therapies, and often unable to be operated upon due to their location.</p>
            card_date: June 14, 1984
            card_author: By Lee Hermiston
            card_aria: desc-a-card
          - card_title: Swinging for the fences in sports management
            card_link_title: View Story
            card_link_url: https://uiowa.edu/
            card_image: ../../images/feature4.jpg
            card_text: <p>Jake Stone is heading to the Baltimore Orioles organization after graduation. He says this was made possible by taking advantage of the opportunities offered by the University of Iowa’s Sport and Recreation Management Program and his work with the Hawkeye baseball team.</p>
            card_date: June 14, 1984
            card_author: By Lee Hermiston
            card_classes: card--enclosed
            card_aria: desc-a-card
          - card_title: Turning the tide for sick seals
            card_link_title: View Story
            card_link_url: https://uiowa.edu/
            card_image: ../../images/feature3.jpg
            card_text: <p>As the attending veterinarian at a marine mammal hospital in Los Angeles, University of Iowa alumna Lauren Palmer aims to rehabilitate and release sick or injured animals—and to help educate people about the ocean’s ecosystem.</p>
            card_date: June 14, 1984
            card_author: By Sara Epstein Moninger
            card_aria: desc-a-card
    display:
      max-width: 100%
