title: Main Menu
hidden: false
order: 4
status: wip
meta:
  dependencies:
    stylesheets:
      - /components/typography/headings/headings.css
      - /components/banner/banner.css
      - /components/headline/headline.css
      - /components/button/button.css
context:
    field_title: Headline
    menu_type: main
    site_type: primary
variants:
  - name: default
    hidden: true
  - name: Main Menu Secondary Horizontal
    hidden: false
    context:
      nav_type: main--secondary--horizontal
  - name: Main Menu Secondary Horizontal - Lined Grey Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--lined-grey-arrow
  - name: Main Menu Secondary Horizontal - Lined Gold Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--lined-gold-arrow
  - name: Main Menu Secondary Horizontal - Grey Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--grey-arrow
  - name: Main Menu Secondary Horizontal - Gold Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--gold-arrow
  - name: Main Menu Secondary Horizontal - Bordered Grey Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--bordered-grey-arrow
  - name: Main Menu Secondary Horizontal - Bordered Gold Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--bordered-gold-arrow
  - name: Main Menu Secondary Horizontal - Triple Lined Grey Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--triple-lined-grey-arrow
  - name: Main Menu Secondary Vertical
    hidden: false
    context:
      nav_type: main--secondary--vertical
