title: Main Menu
hidden: false
order: 4
status: wip
meta:
  dependencies:
    stylesheets:
      - /components/typography/headings/headings.css
      - /components/banner/banner.css
      - /components/headline/headline.css
      - /components/button/button.css
      - /components/background/background.css
context:
    field_title: Headline
    menu_type: main
    site_type: primary
variants:
  - name: default
    hidden: true
  - name: Main Menu Secondary Horizontal
    hidden: false
    context:
      nav_type: main--secondary--horizontal
  - name: Main Menu Secondary Horizontal - Black Background Lined Gold Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--lined-gold-arrow
      menu_bg: bg--black
  - name: Main Menu Secondary Horizontal - Black Brain Background Lined Gold Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--lined-gold-arrow
      menu_bg: bg--black--pattern--brain
  - name: Main Menu Secondary Horizontal - Gold Background Lined Gold Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--lined-gold-arrow
      menu_bg: bg--gold
  - name: Main Menu Secondary Horizontal - Gold Brain Background Lined Gold Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--lined-gold-arrow
      menu_bg: bg--gold--pattern--brain
  - name: Main Menu Secondary Horizontal - Gray Background Lined Gold Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--lined-gold-arrow
      menu_bg: bg--gray
  - name: Main Menu Secondary Horizontal - White Background Lined Gold Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--lined-gold-arrow
      menu_bg: bg--white
  - name: Main Menu Secondary Horizontal - White Brain Background Lined Gold Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--lined-gold-arrow
      menu_bg: bg--white--pattern--brain
  - name: Main Menu Secondary Vertical
    hidden: false
    context:
      nav_type: main--secondary--vertical
