title: Main Menu
hidden: true
order: 4
status: wip
meta:
  dependencies:
    stylesheets:
      - /components/typography/headings/headings.css
      - /components/banner/banner.css
      - /components/headline/headline.css
      - /components/button/button.css
      - /components/background/background.css
context:
    field_title: Headline
    menu_type: main
    site_type: primary
    links_nav:
      title: Additional Navigation
      title_classes: element-invisible
      links:
      - link_nav_text: Admissions
        link_nav_classes:
      - link_nav_text: Academics
        link_nav_classes:
      - link_nav_text: Research
        link_nav_classes:
      - link_nav_text: About
        link_nav_classes:

variants:
  - name: default
    hidden: true
  - name: Main Menu Secondary Horizontal - Black Background
    hidden: false
    context:
      nav_type: main--secondary--horizontal
      menu_bg: bg--black
  - name: Main Menu Secondary Horizontal - Black Brain Background
    hidden: false
    context:
      nav_type: main--secondary--horizontal
      menu_bg: bg--black--pattern--brain
  - name: Main Menu Secondary Horizontal - Gold Background
    hidden: false
    context:
      nav_type: main--secondary--horizontal
      menu_bg: bg--gold
  - name: Main Menu Secondary Horizontal - Gold Brain Background
    hidden: false
    context:
      nav_type: main--secondary--horizontal
      menu_bg: bg--gold--pattern--brain
  - name: Main Menu Secondary Horizontal - Gray Background
    hidden: false
    context:
      nav_type: main--secondary--horizontal
      menu_bg: bg--gray
  - name: Main Menu Secondary Horizontal - White Background
    hidden: false
    context:
      nav_type: main--secondary--horizontal
      menu_bg: bg--white
  - name: Main Menu Secondary Horizontal - White Brain Background
    hidden: true
    context:
      nav_type: main--secondary--horizontal
      menu_bg: bg--white--pattern--brain
  - name: Main Menu Secondary Horizontal - Black Alt Brain Background
    hidden: true
    context:
      nav_type: main--secondary--horizontal
      menu_bg: bg-pattern--brain-black
  - name: Main Menu Secondary Horizontal - Gold Alt Brain Background
    hidden: true
    context:
      nav_type: main--secondary--horizontal
      menu_bg: bg-pattern--brain-reversed

  - name: children
    label: Main Menu Children Secondary Horizontal - Gray Background
    hidden: false
    context:
      nav_type: main--secondary--horizontal
      menu_bg: bg--gray

  - name: Main Menu Secondary Vertical - Black Background
    hidden: true
    context:
      nav_type: main--secondary--vertical
      menu_bg: bg--black
  - name: Main Menu Secondary Vertical - Black Brain Background
    hidden: true
    context:
      nav_type: main--secondary--vertical
      menu_bg: bg--black--pattern--brain
  - name: Main Menu Secondary Vertical - Gold Background
    hidden: true
    context:
      nav_type: main--secondary--vertical
      menu_bg: bg--gold
  - name: Main Menu Secondary Vertical - Gold Brain Background
    hidden: true
    context:
      nav_type: main--secondary--vertical
      menu_bg: bg--gold--pattern--brain
  - name: Main Menu Secondary Vertical - Gray Background
    hidden: false
    context:
      nav_type: main--secondary--vertical
      menu_bg: bg--gray
  - name: Main Menu Secondary Vertical - White Background
    hidden: true
    context:
      nav_type: main--secondary--vertical
      menu_bg: bg--white
  - name: Main Menu Secondary Vertical - White Brain Background
    hidden: true
    context:
      nav_type: main--secondary--vertical
      menu_bg: bg--white--pattern--brain
  - name: Main Menu Secondary Vertical - Black Alt Brain Background
    hidden: true
    context:
      nav_type: main--secondary--vertical
      menu_bg: bg-pattern--brain-black
  - name: Main Menu Secondary Vertical - Gold Alt Brain Background
    hidden: true
    context:
      nav_type: main--secondary--vertical
      menu_bg: bg-pattern--brain-reversed

  - name: Main Menu Sidebar
    hidden: false
    context:
      nav_type: main--sidebar
      links_nav:
        links:
        - link_nav_text: Admissions
          link_nav_classes: item--first
        - link_nav_text: Academics
          link_nav_classes: menuparent--active is-active
          links:
          - link_nav_text: Undergraduate
            link_nav_classes:
          - link_nav_text: Graduate
            link_nav_classes:
          - link_nav_text: International
            link_nav_classes:
          - link_nav_text: Distance and online
            link_nav_classes:
          - link_nav_text: Cost and aid
            link_nav_classes:
        - link_nav_text: Research
          link_nav_classes:
        - link_nav_text: About
          link_nav_classes:
  - name: Main Menu Sidebar Minimal
    hidden: false
    context:
      nav_type: main--sidebar main--sidebar-minimal
      links_nav:
        links:
          - link_nav_text: Admissions
            link_nav_classes: item--first
          - link_nav_text: Academics
            link_nav_classes: menuparent--active is-active
            links:
          - link_nav_text: Research
            link_nav_classes:
          - link_nav_text: About
            link_nav_classes:
  - name: links
    label: Links
    hidden: true
