label: Search Toggle
hidden: true
order: 7
status: wip

variants:
  - name: default
    label: UIowa Search
    hidden: false
    context:
       title: Search this site
       title_2: Search all of uiowa
  - name: bttn
    label: Search Button
    hidden: true
  - name: overlay
    label: Search Overlay
    hidden: true
  - name: primary
    label: Search Overlay Primary
    hidden: true
    context:
       search_type: search--primary

