title: Headline
order: 10
status: wip
tags: ['typography']
hidden: true
context:
  backgrounds: '@background.backgrounds'
  headlines:
    - headline_text: Roboto
      headline_class: ''
    - headline_text: Antonio
      headline_class: headline--uppercase
    - headline_text: Antonio - Underline
      headline_class: headline--underline headline--uppercase
    - headline_text: Antonio - Highlighted
      headline_class: headline--uppercase headline--highlight
    - headline_text: Antonio - Single <span>Word</span> Highlighted
      headline_class: headline--uppercase
    - headline_text: Zilla Slab (Serif)
      headline_class: headline--serif
    - headline_text: Zilla Slab (Serif) - Underlined
      headline_class: headline--serif headline--underline
    - headline_text: Zilla Slab (Serif) - Highlighted
      headline_class: headline--serif headline--highlight
