title: Button
order: 10
status: wip
collated: false
meta:
  dependencies:
    stylesheets:
      - /components/colors/colors.css
      - /components/background/background.css
display:
  width: 100%
variants:
  - name: default
    hidden: false
    context:
      button_text: More News
      button_type: bttn--tertiary bttn--caps
      button_link: https://www.example.com
      button_icon: yes
  - name: Button Gold Bg
    hidden: true
    context:
      button_text: More News
      button_type: bttn--primary bttn--caps
      button_link: https://www.example.com
      button_icon: yes
  - name: Button Black Bg
    hidden: true
    context:
      button_text: More News
      button_type: bttn--secondary bttn--caps
      button_link: https://www.example.com
      button_icon: yes
  - name: Button Outline
    hidden: true
    context:
      button_text: More News
      button_type: bttn--outline bttn--tertiary bttn--caps
      button_icon: yes
  - name: Button Outline Sans-Serif
    notes: This variation is used for Card Link component
    hidden: true
    context:
      button_text: More News
      button_type: bttn--outline bttn--tertiary bttn--sans-serif
      button_icon: yes
  - name: Button Outline Sans-Serif Background
    notes: This variation is used for the Hero Image component
    hidden: true
    context:
      button_text: More News
      button_type: bttn--secondary bttn--sans-serif bttn--outline bttn--outline
      button_link: https://www.example.com
      button_icon:
  - name: Button Sans-Serif
    notes: This variation is used for Card Link component
    hidden: true
    context:
      button_text: More News
      button_type: bttn--link bttn--sans-serif
      button_icon: yes
  - name: row
    label: Collection
    hidden: false
    context:
      items:
        - button_text: More News
          button_type: bttn--tertiary bttn--caps
          button_link: https://www.example.com
          button_icon: yes
        - button_text: More News
          button_type: bttn--primary bttn--caps
          button_link: https://www.example.com
          button_icon: yes
        - button_text: More News
          button_type: bttn--secondary bttn--caps
          button_link: https://www.example.com
          button_icon: yes
        - button_text: More News
          button_type: bttn--outline bttn--tertiary bttn--caps
          button_icon: yes
        - button_text: More News
          button_type: bttn--outline bttn--tertiary bttn--sans-serif
          button_icon: yes
        - button_text: More News
          button_type: bttn--secondary bttn--sans-serif bttn--outline bttn--outline
          button_link: https://www.example.com
          button_icon:
        - button_text: More News
          button_type: bttn--link bttn--sans-serif
          button_icon: yes

