title: Stat
hidden: false
order: 30
meta:
  dependencies:
    stylesheets:
      - /components/colors/colors.css
status: wip
context:
  stat_title: '15:1'
  stat_summary: 'student-to-faculty ratio'
  stat_content: 'Among the top 2% of universities worldwide.'
  stat_image: '../../images/examples/stat-1.jpg'
  stat_image_position: 'top'
  stat_pattern:  '../../images/brain.png'
  stat_prefix:
  stat_suffix:
  stat_classes: 'element--flex-center bg-pattern--brain'

variants:
  - name: default
    hidden: false
  - name: horizontal
    label: Stat Horizontal
    hidden: false
    context:
      stat_classes: 'stat--horizontal bg--black'
  - name: row
    label: Collection
    context:
      row:
        items:
          - stat_title: '15:1'
            stat_summary: 'student-to-faculty ratio'
            stat_content: ''
            stat_image: '../../images/examples/stat-1.jpg'
            stat_image_position: 'top'
            stat_pattern:  '../../images/brain.png'
            stat_prefix:
            stat_suffix:
            stat_classes: 'element--flex-center bg-pattern--brain'
          - stat_title: '78'
            stat_summary: 'of classes have fewer than 30 students'
            stat_content: ''
            stat_image: '../../images/examples/stat-2.jpg'
            stat_image_position: 'bottom'
            stat_pattern:  '../../images/brain.png'
            stat_prefix:
            stat_suffix: '%'
            stat_classes: 'element--flex-center bg-pattern--brain'
          - stat_title: '34'
            stat_summary: 'best public university, u.s. news & world report'
            stat_content: ''
            stat_image: '../../images/examples/stat-3.jpg'
            stat_image_position: 'top'
            stat_pattern: '../../images/brain.png'
            stat_prefix: '#'
            stat_suffix:
            stat_classes: 'element--flex-center bg-pattern--brain'
          - stat_title: '5,000'
            stat_summary: 'courses offered every year'
            stat_content: ''
            stat_image:
            stat_pattern:
            stat_prefix: '+'
            stat_suffix:
            stat_classes: 'element--flex-center bg-pattern--brain'


