title: Tables
status: wip
order: 10
collated: false
meta:
  dependencies:
    stylesheets:
      - /components/typography/headings/headings.css
      - /components/typography/lists/lists.css
      - /components/typography/paragraph/paragraph.css
context:
    test: test
