title: Hero
order: 0
status: wip
hidden: false
collate: false
meta:
  dependencies:
    stylesheets:
      - /components/headline/headline.css
      - /components/button/button.css
      - /components/colors/colors.css
context:
  hero_type: image
  hero_size: large
  hero_content:
  hero_image: '../../assets/images/widescreen__2592_x_1458/pano.jpg'
  hero_vertical_alignment: hero--vertical-center
  hero_horizontal_alignment: hero--horizontal-center
  hero_title: 'We’re in this together'
  hero_text: '<p>Every Hawkeye has a role to play in <a href="https://uiowa.edu">preventing</a> the spread of COVID-19.
Find out what Iowa’s doing—and what you can do—to make your return to campus safer.</p>'
  hero_link_title: View Story
  hero_link_url: https://uiowa.edu/
  hero_link_classes: bttn bttn--secondary bttn--caps
  hero_aria: desc-a-card
  hero_overlay: gradient-center
  hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
  hero_classes: bg--black
variants:
  - name: default
    label: Large centered hero
    hidden: false
    context:
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
  - name: large_centered_left_hero
    label: Large centered left hero
    notes: This version uses a headline with a gold background highlight with the button using a secondary color scheme.
    context:
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      hero_vertical_alignment: hero--vertical-center
      hero_horizontal_alignment: hero--horizontal-left
  - name: large_lower_left_hero
    label: Large lower left hero
    notes: This version can also be used for the page title hero variant and uses a vertical gradient that doesn't extend as far as the default centered gradient.
    context:
      hero_content:
      hero_vertical_alignment: hero--vertical-bottom
      hero_horizontal_alignment: hero--horizontal-left
      hero_title: 'We’re in this together'
      hero_overlay: gradient-center-left
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_link_classes: bttn bttn--primary bttn--caps
  - name: large_lower_centered_hero
    label: Large lower centered hero
    notes: This version can also be used for the page title hero variant and uses a vertical gradient that doesn't extend as far as the default centered gradient.
    context:
      hero_content:
      hero_vertical_alignment: hero--vertical-bottom
      hero_horizontal_alignment: hero--horizontal-center
      hero_title: 'We’re in this together'
      hero_overlay: gradient-center-left
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_link_classes: bttn bttn--primary bttn--caps
  - name: large_lower_left_highlighted_hero
    label: Large lower left highlighted hero
    notes: This version uses a headline with a gold background highlight with the button using a secondary color scheme.
    context:
      hero_vertical_alignment: hero--vertical-bottom
      hero_horizontal_alignment: hero--horizontal-left
      hero_title: 'We’re in this together'
      hero_overlay: gradient-center-left
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      hero_link_classes: bttn bttn--primary bttn--caps
  - name: large_lower_left_highlighted_hero_caps
    label: Large lower left highlighted hero caps
    notes: This version uses a headline with a gold background highlight with the button using a secondary color scheme.
    context:
      hero_vertical_alignment: hero--vertical-bottom
      hero_horizontal_alignment: hero--horizontal-left
      hero_title: 'We’re in this together'
      hero_overlay: gradient-center-left
      hero_title_classes: 'bold-headline--caps bold-headline bold-headline--highlight'
  - name: large lower_centered_highlighted_hero
    label: Large lower centered highlighted hero
    notes: This version uses a headline with a gold background highlight with the button using a secondary color scheme.
    context:
      hero_vertical_alignment: hero--vertical-bottom
      hero_horizontal_alignment: hero--horizontal-center
      hero_title: 'We’re in this together'
      hero_overlay: gradient-center-left
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
  - name: medium_centered_left_hero
    label: Medium centered left hero
    notes: The banner variant has a smaller vertical height, smaller heading size, and lighter paragraph font weight. This version uses a horizontal left gradient.  The content is vertically centered and left aligned.
    context:
      hero_vertical_alignment: hero--vertical-center
      hero_horizontal_alignment: hero--horizontal-left
      hero_size: medium
      hero_title: 'We’re in this together'
      hero_overlay: gradient-left
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_link_classes: bttn bttn--primary bttn--caps
  - name: medium_centered_hero
    label: Medium centered hero
    notes: The banner variant has a smaller vertical height, smaller heading size, and lighter paragraph font weight. This version uses a solid black opacity.  The content is vertically and horizontally centered.
    context:
      hero_vertical_alignment: hero--vertical-center
      hero_horizontal_alignment: hero--horizontal-center
      hero_size: medium
      hero_title: 'We’re in this together'
      hero_overlay: solid-opacity
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_link_classes: bttn bttn--primary bttn--caps
  - name: medium_lower_left_hero
    label: Medium lower left hero
    notes: The banner variant has a smaller vertical height, smaller heading size, and lighter paragraph font weight. This version uses a horizontal left gradient.  The content is vertically centered and left aligned.
    context:
      hero_vertical_alignment: hero--vertical-bottom
      hero_horizontal_alignment: hero--horizontal-left
      hero_size: medium
      hero_title: 'We’re in this together'
      hero_overlay: gradient-left
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_link_classes: bttn bttn--primary bttn--caps
  - name: medium_centered_left_bg_color_hero
    label: Medium centered left w/ background pattern hero
    notes: The banner variant has a smaller vertical height, smaller heading size, and lighter paragraph font weight. This version uses a horizontal left gradient.  The content is vertically centered and left aligned.
    context:
      hero_size: medium
      hero_type:
      hero_vertical_alignment: hero--vertical-center
      hero_horizontal_alignment: hero--horizontal-left
      hero_title: 'We’re in this together'
      hero_overlay: solid-opacity
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_link_classes: bttn bttn--primary bttn--caps
      hero_classes: bg-pattern--brain-black
  - name: medium_centered_left_bg_color_reversed
    label: Medium centered left w/ background pattern reversed hero
    notes: The banner variant has a smaller vertical height, smaller heading size, and lighter paragraph font weight. This version uses a horizontal left gradient.  The content is vertically centered and left aligned.
    context:
      hero_size: medium
      hero_type:
      hero_vertical_alignment: hero--vertical-center
      hero_horizontal_alignment: hero--horizontal-left
      hero_title: 'We’re in this together'
      hero_overlay:
      hero_title_classes: 'bold-headline--serif bold-headline'
      hero_link_classes: bttn bttn--primary bttn--caps
      hero_classes: bg-pattern--brain
  - name: medium_centered_left_bg_color_gold
    label: Medium centered left w/ gold background pattern
    notes: The banner variant has a smaller vertical height, smaller heading size, and lighter paragraph font weight. This version uses a horizontal left gradient.  The content is vertically centered and left aligned.
    context:
      hero_size: medium
      hero_type:
      hero_vertical_alignment: hero--vertical-center
      hero_horizontal_alignment: hero--horizontal-left
      hero_title: 'We’re in this together'
      hero_overlay:
      hero_title_classes: 'bold-headline--serif bold-headline'
      hero_classes: bg-pattern--brain-reversed
  - name: small_centered_left_hero
    label: Small centered left hero
    notes: This version of the banner has a very small height and is meant for a very small amount of text.
    context:
      hero_size: small
      hero_vertical_alignment: hero--vertical-center
      hero_horizontal_alignment: hero--horizontal-left
      hero_title: 'We’re in this together'
      hero_overlay: gradient-left
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_link_classes: bttn bttn--primary bttn--caps
  - name: small_centered_hero
    label: Small centered hero
    notes: This is a version of the small banner that is centered with a solid black opacity
    context:
      hero_size: small
      hero_vertical_alignment: hero--vertical-center
      hero_horizontal_alignment: hero--horizontal-center
      hero_title: 'We’re in this together'
      hero_overlay: solid-opacity
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_link_classes: bttn bttn--primary bttn--caps
  - name: small_centered_bg_color_hero
    label: Small centered w/ pattern hero
    notes: This is a version of the small banner that is centered with a solid black opacity
    context:
      hero_size: small
      hero_type:
      hero_vertical_alignment: hero--vertical-center
      hero_horizontal_alignment: hero--horizontal-center
      hero_title: 'We’re in this together'
      hero_overlay: solid-opacity
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      hero_classes: bg-pattern--brain-black
  - name: small_centered_bg_color_reversed_hero
    label: Small centered w/ pattern reversed hero
    notes: This is a version of the small banner that is centered with a solid black opacity
    context:
      hero_size: small
      hero_type:
      hero_vertical_alignment: hero--vertical-center
      hero_horizontal_alignment: hero--horizontal-center
      hero_title: 'We’re in this together'
      hero_overlay:
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      hero_classes: bg-pattern--brain
  - name: video
    label: Video
    hidden: false
    notes: The Hero video variant is vertically centered with a play/pause button positioned in the lower left-hand corner.
    context:
      hero_type: video
      hero_content:
      hero_vertical_alignment: hero--vertical-center
      hero_horizontal_alignment: hero--horizontal-center
      hero_overlay: solid-opacity
      hero_title: 'We’re in this together'
      hero_image: ../../images/hero-image.jpg
      hero_image_alt: 'View of University of Iowa Campus'
      hero_video: '../../assets/video/home.mp4'
      hero_link_classes: bttn bttn--primary bttn--caps
