hidden: false
meta:
  dependencies:
    stylesheets:
      - /components/colors/colors.css
context:
  image_sizes: (min-width:1310px) 1310px, 100vw
  image_srcs:
    - path: ../../assets/images/widescreen__384_x_216/bg-image-square.jpg
      size: 384w
    - path: ../../assets/images/widescreen__768_x_432/bg-image-square.jpg
      size: 768w
    - path: ../../assets/images/widescreen__1024_x_576/bg-image-square.jpg
      size: 1024w
    - path: ../../assets/images/widescreen__1312_x_738/bg-image-square.jpg
      size: 1312w
    - path: ../../assets/images/widescreen__1920_x_1080/bg-image-square.jpg
      size: 1920w
    - path: ../../assets/images/widescreen__2592_x_1458/bg-image-square.jpg
      size: 2592w
  display:
    max-width: 768px
variants:
  - name: default
    label: Image
    status: null
    hidden: true
    context:
      image_sizes: (min-width:1310px) 1310px, 100vw
      image_srcs:
        - path: ../..=/assets/images/widescreen__384_x_216/bg-image.jpg
          size: 384w
        - path: ../../assets/images/widescreen__768_x_432/bg-image.jpg
          size: 768w
        - path: ../../assets/images/widescreen__1024_x_576/bg-image.jpg
          size: 1024w
        - path: ../../assets/images/widescreen__1312_x_738/bg-image.jpg
          size: 1312w
        - path: ../../assets/images/widescreen__1920_x_1080/bg-image.jpg
          size: 1920w
        - path: ../../assets/images/widescreen__2592_x_1458/bg-image.jpg
          size: 2592w
  - name: border
    label: Border
    hidden: false
    context:
      image_classes: media--border
    display:
      max-width: 768px
  - name: circle
    label: Circle
    hidden: false
    context:
      image_classes: media--circle
    display:
      max-width: 768px
  - name: circle-border
    label: Circle w/border
    hidden: false
    context:
      image_classes: media--border media--circle
    display:
      max-width: 768px
  - name: circle-gray
    label: Circle w/ gray bg
    hidden: false
    context:
      image_container_classes: bg--gray
      image_classes: media--border media--circle
    display:
      max-width: 768px
  - name: circle-gold
    label: Circle w/ gold bg
    hidden: false
    context:
      image_container_classes: bg--gold
      image_classes: media--border media--circle
    display:
      max-width: 768px
  - name: circle-black
    label: Circle w/ black bg
    hidden: false
    context:
      image_container_classes: bg--black
      image_classes: media--border media--circle
    display:
      max-width: 768px
