title: Page Layout
label: Page Layouts
hidden: true
order: 10
status: wip
context:
  site_name: Department of College
  site_slogan: College Name
  site_front: /
  site_title: Home Page
  header_alignment: site-header__default
  menu_type: superfish
  site_type: primary
  header_type: site-header--secondary
  nav_type: navbar--secondary
  button:
    text: Call to Action
    link: https://example2.com
    type: bttn--basic bttn--tertiary
variants:
  - name: default
    label: Default Secondary Superfish
