title: Off Canvas Menu
hidden: true
order: 4
status: wip

variants:
  - name: default
    label: Off Canvas
    hidden: true
  - name: bttn
    label: Off Canvas Button
    hidden: true
  - name: drawer
    label: Off Canvas Drawer
    hidden: true
