title: Banner
label: Banner
order: 39
status: wip
hidden: false
collate: false
meta:
  dependencies:
    stylesheets:
      - /components/headline/headline.css
      - /components/button/button.css
      - /components/colors/colors.css
context:
  banner_type: image
  banner_size: large
  banner_content:
  banner_image: '../../assets/images/widescreen__2592_x_1458/pano.jpg'
  banner_vertical_alignment: banner--vertical-center
  banner_horizontal_alignment: banner--horizontal-center
  banner_title: 'We’re in this together'
  banner_text: '<p>Every Hawkeye has a role to play in <a href="https://uiowa.edu">preventing</a> the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you can do—to make your return to campus safer.</p>'
  banner_link_title: View Story
  banner_link_url: https://uiowa.edu/
  banner_link_classes: bttn bttn--secondary bttn--caps
  banner_aria: desc-a-card
  banner_overlay: gradient-center
  banner_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
  banner_classes:
variants:
  - name: default
    label: Large, content centered
    hidden: false
    context:
      banner_title_classes: bold-headline--serif bold-headline bold-headline--negative
  - name: large_centered_left_banner
    label: Large centered left banner
    hidden: true
    context:
      banner_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
  - name: large_lower_left_banner
    label: Large lower left banner
    hidden: true
    context:
      banner_content:
      banner_vertical_alignment: banner--vertical-bottom
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'We’re in this together'
      banner_overlay: gradient-center-left
      banner_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      banner_link_classes: bttn bttn--primary bttn--caps
  - name: large_lower_centered_banner
    label: Large lower centered banner
    hidden: true
    context:
      banner_content:
      banner_vertical_alignment: banner--vertical-bottom
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'We’re in this together'
      banner_overlay: gradient-center-left
      banner_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      banner_link_classes: bttn bttn--primary bttn--caps
  - name: large_lower_left_highlighted_banner
    label: Large lower left highlighted banner
    hidden: true
    context:
      banner_vertical_alignment: banner--vertical-bottom
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'We’re in this together'
      banner_overlay: gradient-center-left
      banner_title_classes: 'bold-headline--caps bold-headline bold-headline--highlight'
      banner_link_classes: bttn bttn--primary bttn--caps
  - name: large_lower_left_highlighted_banner_caps
    label: Large lower left highlighted banner caps
    hidden: true
    context:
      banner_vertical_alignment: banner--vertical-bottom
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'We’re in this together'
      banner_overlay: gradient-center-left
      banner_title_classes: 'bold-headline--caps bold-headline bold-headline--highlight'
  - name: large lower_centered_highlighted_banner
    label: Large lower centered highlighted banner
    hidden: true
    context:
      banner_vertical_alignment: banner--vertical-bottom
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'We’re in this together'
      banner_overlay: gradient-center-left
      banner_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
  - name: medium_centered_left_banner
    label: Medium centered left banner
    hidden: true
    context:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_size: medium
      banner_title: 'We’re in this together'
      banner_overlay: gradient-left
      banner_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      banner_link_classes: bttn bttn--primary bttn--caps
  - name: medium_centered_left_banner_reversed
    label: Medium centered left banner reversed
    hidden: true
    context:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_size: medium
      banner_title: 'We’re in this together'
      banner_overlay: gradient-left-reversed
      banner_title_classes: 'bold-headline--serif bold-headline'
      banner_link_classes: bttn bttn--primary bttn--caps
  - name: medium_centered_banner
    label: Medium, content centered
    context:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_size: medium
      banner_title: 'We’re in this together'
      banner_overlay: solid-opacity
      banner_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      banner_link_classes: bttn bttn--primary bttn--caps
  - name: medium_lower_left_banner
    label: Medium lower left banner
    hidden: true
    context:
      banner_vertical_alignment: banner--vertical-bottom
      banner_horizontal_alignment: banner--horizontal-left
      banner_size: medium
      banner_title: 'We’re in this together'
      banner_overlay: gradient-left
      banner_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      banner_link_classes: bttn bttn--primary bttn--caps
  - name: medium_centered_left_bg_color_banner
    label: Medium centered left w/ background pattern banner
    hidden: true
    context:
      banner_size: medium
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'We’re in this together'
      banner_overlay:
      banner_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      banner_link_classes: bttn bttn--primary bttn--caps
      banner_classes: bg-pattern--brain-black
  - name: medium_centered_left_bg_color_reversed
    label: Medium centered left w/ background pattern reversed banner
    hidden: true
    context:
      banner_size: medium
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'We’re in this together'
      banner_overlay:
      banner_title_classes: 'bold-headline--serif bold-headline'
      banner_link_classes: bttn bttn--primary bttn--caps
      banner_classes: bg-pattern--brain
  - name: medium_centered_left_bg_color_gold
    label: Medium, content left-aligned, centered vertically w/ gold background pattern
    hidden:
    context:
      banner_size: medium
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'We’re in this together'
      banner_overlay:
      banner_title_classes: 'bold-headline--serif bold-headline'
      banner_classes: bg-pattern--brain-reversed
  - name: small_centered_left_banner
    label: Small centered left banner
    hidden: true
    context:
      banner_size: small
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-left
      banner_title: 'We’re in this together'
      banner_overlay: gradient-left
      banner_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      banner_link_classes: bttn bttn--primary bttn--caps
  - name: small_centered_banner
    label: Small, content centered
    context:
      banner_size: small
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'We’re in this together'
      banner_overlay: solid-opacity
      banner_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      banner_link_classes: bttn bttn--primary bttn--caps
  - name: small_centered_bg_color_banner
    label: Small, content centered w/ black background pattern
    hidden: false
    context:
      banner_size: small
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'We’re in this together'
      banner_overlay:
      banner_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      banner_classes: bg-pattern--brain-black
  - name: small_centered_bg_color_reversed_banner
    label: Small centered w/ pattern reversed banner
    hidden: true
    context:
      banner_size: small
      banner_type:
      banner_vertical_alignment: banner--vertical-center
      banner_horizontal_alignment: banner--horizontal-center
      banner_title: 'We’re in this together'
      banner_overlay:
      banner_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      banner_classes: bg-pattern--brain
