title: Nav Bar
status: wip
order: 1
meta:
  dependencies:
    scripts:
      - /components/proposals/src/navbar/navbar.js
      - /components/proposals/src/navbar/navbar.dropDown.js
      - /components/proposals/src/navbar/navbar.menuToggle.js
      - /components/proposals/src/navbar/navbar.responsive.js
    stylesheets:
      - /components/branding/logo/logo.css
      - /components/branding/site-name/site-name.css
      - /components/branding/parent-site-name/parent-site-name.css
      - /components/branding/iowa-bar/iowa-bar.css


