title: CTA Block Default
order: 3
status: wip
hidden: false
meta:
  dependencies:
    stylesheets:
      - /components/background/background.css
      - /components/headline/headline.css
      - /components/button/button.css
      - /components/colors/colors.css
variants:
  - name: default
    hidden: false
    context:
        cta_title: Create Your Path
        cta_summary: Iowa blends leadership in the arts with pioneering scientific research, helping students carve their own unique path–wherever it leads.
        cta_classes:
        cta_link_url: https://uiowa.edu/
        cta_link_title: Request Information
        cta_link_classes:
  - name: default-left
    hidden: false
    context:
        cta_title:
        cta_summary: Iowa blends leadership in the arts with pioneering scientific research, helping students carve their own unique path–wherever it leads.
        cta_classes: element--left
        cta_link_url: https://uiowa.edu/
        cta_link_title: Request Information
        cta_link_classes:
  - name: gold
    label: CTA Block Gold Centered
    hidden: false
    context:
        cta_title: Create Your Path
        cta_summary: Iowa blends leadership in the arts with pioneering scientific research, helping students carve their own unique path–wherever it leads.
        cta_classes:  bg--gold
        cta_link_url: https://uiowa.edu/
        cta_link_title: Request Information
        cta_link_classes:
  - name: gold-left
    label: CTA Block Gold Left
    hidden: false
    context:
        cta_title: Create Your Path
        cta_summary: Iowa blends leadership in the arts with pioneering scientific research, helping students carve their own unique path–wherever it leads.
        cta_classes: element--left bg--gold
        cta_link_url: https://uiowa.edu/
        cta_link_title: Request Information
        cta_link_classes:
  - name: black
    label: CTA Block Black Centered
    hidden: false
    context:
        cta_title: Create Your Path
        cta_summary: Iowa blends leadership in the arts with pioneering scientific research, helping students carve their own unique path–wherever it leads.
        cta_classes: bg--black
        cta_link_url: https://uiowa.edu/
        cta_link_title: Request Information
        cta_link_classes:
  - name: black-left
    label: CTA Block Black Left
    hidden: false
    context:
        cta_title:
        cta_summary: Iowa blends leadership in the arts with pioneering scientific research, helping students carve their own unique path–wherever it leads.
        cta_classes: element--left bg--black
        cta_link_url: https://uiowa.edu/
        cta_link_title: Request Information
        cta_link_classes:
