title: Grid Panel
name: Grid Panel
order: 99
status: wip
collate: false
meta:
  dependencies:
    stylesheets:
      - /components/headline/headline.css
      - /components/highlight/highlight.css
      - /components/button/button.css
      - /components/typography/headings/headings.css
variants:
  - name: default
    hidden: false
    context:
      grid_type: asymmetrical
      grid_content_position: second
      grid_panel_first_column : grid-panel__column-image-left
      grid_panel_second_column : grid-panel__column-content-right grid-panel__content
      grid_panel_image: '<img class="grid-panel__img" src="../../assets/images/viewbook/sections/0315.jpg" alt="Alt Text" />'
      grid_panel_content: '<p>The University of Iowa blends big-school opportunities with close, personal support to help you excel. We remove the barriers between arts and science, between students and faculty—but most of all, between you and anything you’d like to explore.</p>
	<p>How many universities have both a state-of-the-art children’s hospital and
		a 3,883-pipe Klais organ? Or helped build the Voyager I satellite and the very first creative writing degree program? Just one: Iowa.</p>'
      grid_panel_headline: 'We Work <span>Together</span>'
      button:
        text: View Academic Opportunities
        type: bttn bttn--secondary bttn--caps
        link: https://admissions.uiowa.edu/academics/academics
        icon: yes
