name: image
label: Image
hidden: true
context:
  image_sizes: (min-width:1310px) 1310px, 100vw
  image_srcs:
    - path: ../../assets/images/widescreen__384_x_216/bg-image.jpg
      size: 384w
    - path: ../../assets/images/widescreen__768_x_432/bg-image.jpg
      size: 768w
    - path: ../../assets/images/widescreen__1024_x_576/bg-image.jpg
      size: 1024w
    - path: ../../assets/images/widescreen__1312_x_738/bg-image.jpg
      size: 1312w
    - path: ../../assets/images/widescreen__1920_x_1080/bg-image.jpg
      size: 1920w
    - path: ../../assets/images/widescreen__2592_x_1458/bg-image.jpg
      size: 2592w
