title: Main Menu
hidden: false
order: 4
status: wip
meta:
  dependencies:
    stylesheets:
      - /components/typography/headings/headings.css
      - /components/banner/banner.css
      - /components/headline/headline.css
      - /components/button/button.css
context:
    field_title: Headline
    menu_type: main
    site_type: primary
variants:
  - name: default
    hidden: true
  - name: Main Menu Secondary Horizontal
    hidden: false
    context:
      nav_type: main--secondary--horizontal
  - name: Main Menu Secondary Horizontal - Grey Background Lined Gold Arrow
    hidden: false
    context:
      nav_type: main--secondary--horizontal main--secondary--horizontal--lined-gold-arrow
      menu_bg: menu-container--bg-grey
  - name: Main Menu Secondary Vertical
    hidden: false
    context:
      nav_type: main--secondary--vertical
