title: Carousels
status: prototype
order: 40
hidden: false
context:
  display_title: false
  label_hidden: false
  label: Cookie Carousel
  content:
    title:
      Carousel
  items:
    - title: Chocolate Chip Cookie
      classes: any classes
      image: https://media.glamour.com/photos/5e9b5651689027000853a1f7/16:9/w_1280,c_limit/GettyImages-507373042.jpg
      caption: |
        Among the most popular of all cookie types, the chocolate chip cookie's invention was a happy accident. In 1930, Ruth Graves Wakefield, who ran the Toll House Inn in Whitman, Massachusetts, ran out of baker's chocolate and substituted for it with pieces of Nestle's® semi-sweet chocolate.
    - title: Sugar Cookie
      classes: any classes
      image: https://assets.bonappetit.com/photos/57c5c42f6a6acdf3485df9fb/16:9/w_1280,c_limit/SUGAR-COOKIES.jpg
      caption: |
        The sugar cookie is like the vanilla ice cream of cookies—everyone likes it but few claim it as their favorite. Basic ingredients like sugar, flour, butter, eggs, and vanilla make up this popular cookie type.
    - title: Snickerdoodle Cookies
      classes: any classes
      image: https://rucookiemunchers.com/wp-content/uploads/2018/08/snickerdoodle-1280x720.jpg
      caption: |
        Although the origin of this beloved cookie is up for debate, there's no doubt it's a favorite during the holidays. Snickerdoodles are a type of drop cookie (any cookie that is formed by dropping spoonfuls of dough directly onto a baking sheet) that is coated in cinnamon and sugar.