title: Headlines
name: headlines
status: wip
order: 10
collated: false
meta:
  dependencies:
    stylesheets:
      - /components/headline/headline.css
      - /components/background/background.css
context:
    backgrounds: '@background.backgrounds'
    headlines: '@headline.headlines'
