title: Headlines
name: headlines
status: wip
order: 10
collated: false
meta:
  dependencies:
    stylesheets:
      - /components/typography/headings/headings.css
      - /components/background/background.css
context:
    backgrounds: '@background.backgrounds'
    headlines: '@headline.headlines'
