title: Internal Navigation - Horizontal
hidden: true
order: 4
status: wip
context:
  field_title: Headline
  menu_type: main
  site_type: primary
  nav_classes: 'uids-menu main--secondary--horizontal'
  items:
    - text: Undergraduate Admissions
      url: '#'
    - text: Graduate Admissions
      url: '#'
    - text: International Students
      url: '#'
    - text: Online Instruction
      url: '#'
    - text: Cost and Aid
      url: '#'
variants:
  - name: Internal Navigation - Vertical
    context:
      nav_classes: 'uids-menu main--secondary--vertical'
