title: Program
status: wip
order: 30
hidden: false
meta:
  dependencies:
    stylesheets:
      - /components/button/button.css
      - /components/headline/headline.css
      - /components/typography/lists/lists.css
      - /components/typography/headings/headings.css
      - /components/typography/paragraph/paragraph.css
context:
  program_cta_excerpt: <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
  program_cta_title: 'Want to get started?'
  program_cta_link_title: 'Learn More'
  program_cta_link_url: https://uiowa.edu/
  program_description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.'
  program_excerpt: 'A list of objectives learned over the course of studies:<ul><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li><li>Sed do eiusmod tempor incidiunt ut labore.</li><li>Ut enim ad minim veniam, quis nostrud.</li><li>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</li><li>Sed do eiusmod tempor incidiunt ut labore.</li><li>Ut enim ad minim veniam, quis nostrud.</li></ul>'
  program_excerpt_title: 'Learning Objectives'
  program_title: 'Master of Arts in Indisciplinary Studies'
  program_bottom_cta_classes: 'bold-headline bold-headline--serif'
  bttn_class: bttn bttn--primary bttn--caps
variants:
  - name: default
    label: Program
    hidden: false
    context:
      program_title_level: h2
      program_title_classes: bold-headline bold-headline--serif
  - name: Underlined
    hidden: false
    context:
      program_bottom_cta_classes: 'bold-headline bold-headline--serif bold-headline--underline'

