label: Logo
hidden: false
order: 6
status: wip
context:
    logo_path: ../../images/uiowa-secondary.svg#logo
    logo_path_2: ../../images/uiowa.svg#uiowa-logo
    logo_path_3: ../../images/uiowa-left-01.svg#logo
    logo_color: logo__icon--secondary
    path: https://www.uiowa.edu

variants:
  - name: default
    label: UIOWA Logo
    hidden: false

  - name: tab
    label: Tab
    hidden: false
    context:
      logo_path: ../../images/uiowa-secondary.svg#logo
      logo_path_png: ../../images/uiowa-primary.png
      logo_color: logo-icon--secondary
      logo_classes: logo-icon--tab
