title: Accordions
status: ready
order: 40
meta:
  dependencies:
    stylesheets:
      - /components/background/background.css
      - /components/blockquote/blockquote.css
      - /components/typography/lists/lists.css
      - /components/typography/paragraph/paragraph.css
hidden: false
context:
  multiselectable: false
  items:
    - title: Chocolate Chip Cookie
      expanded: true
      content: |
        <p>Among the most popular of all cookie types, the chocolate chip cookie's invention was a happy accident. In 1930, Ruth Graves Wakefield, who ran the Toll House Inn in Whitman, Massachusetts, ran out of baker's chocolate and substituted for it with pieces of Nestle's® semi-sweet chocolate. </p>
    - title: Sugar Cookie
      content: |
        <p>The sugar cookie is like the vanilla ice cream of cookies—everyone likes it but few claim it as their favorite. Basic ingredients like sugar, flour, butter, eggs, and vanilla make up this popular cookie type.</p>
    - title: Snickerdoodle Cookies
      content: |
        <p>Although the origin of this beloved cookie is up for debate, there's no doubt it's a favorite during the holidays. Snickerdoodles are a type of drop cookie (any cookie that is formed by dropping spoonfuls of dough directly onto a baking sheet) that is coated in cinnamon and sugar. </p>
    - title: Oatmeal Raisin
      content: |

        <p>Lorem ipsum dolor sit amet. Aut quia odio eum esse consequatur et dolor similique At consequuntur asperiores ut eius voluptas. Qui officiis modi eum possimus iusto eum quam eaque. Est aspernatur officiis a porro rerum eum nihil sint est iure quidem qui dicta cumque ex omnis temporibus. Eum iste pariatur et expedita unde qui vitae possimus nam voluptas esse aut ullam quam. Eum tempora fugit et fugit recusandae sed ipsa corrupti et labore asperiores in fuga atque est amet aliquid ut nihil animi.</p>

        <p>Vel laboriosam magni vel accusamus sint eum neque rerum et similique blanditiis est voluptatibus voluptas ea fugiat quas. Qui laudantium minima aut iure totam ut quibusdam dolorem rem dolor accusamus eum reiciendis ipsa qui facere nisi non ratione quia. Vel exercitationem optio sed eaque quisquam in voluptatem dolorem sed voluptas voluptas est ratione tenetur. Sit veritatis error <a href="https://www.loremipzum.com" target="_blank">Cum ipsam et veritatis similique et sapiente velit</a>. At repudiandae nisi 33 galisum quia est voluptatem odit ut placeat omnis sit impedit voluptatem.</p>

        <blockquote>
        <p>Sit veritatis error <a href="https://www.loremipzum.com" target="_blank">Cum ipsam et veritatis similique et sapiente velit</a>. At repudiandae nisi 33 galisum quia est voluptatem odit ut placeat omnis sit impedit voluptatem.</p>
        </blockquote>

        <p>Et veniam odit aut consequatur illum <a href="https://www.loremipzum.com" target="_blank">Aut reiciendis et adipisci laboriosam qui omnis culpa aut repudiandae sapiente</a>. Ut quae dolor qui odit fuga eos laboriosam reiciendis sed laudantium accusantium. Est minus sint eum porro adipisci qui sunt ipsum. Qui odio Quis ut saepe laborum et dolores animi aut esse necessitatibus? Quo dolores sunt et adipisci consectetur id enim suscipit. Aut maiores officiis et galisum minima id aliquid ullam. Et consequuntur cupiditate ut placeat velit ut inventore neque ab suscipit natus qui quaerat voluptatem. Et esse suscipit est maiores delectus et placeat quia in dolorum fuga. Est fugit odit est fugiat dolores qui error quia est incidunt quis sed repudiandae asperiores et internos quia!</p>

        <ul><li>Vel exercitationem optio sed eaque quisquam in voluptatem dolorem sed voluptas voluptas est ratione tenetur. Sit veritatis error <a href="https://www.loremipzum.com" target="_blank">Cum ipsam et veritatis similique et sapiente velit</a>. At repudiandae nisi 33 galisum quia est voluptatem odit ut placeat omnis sit impedit voluptatem.</li>
        <li>Et veniam odit aut consequatur illum <a href="https://www.loremipzum.com" target="_blank">Aut reiciendis et adipisci laboriosam qui omnis culpa aut repudiandae sapiente</a>. Ut quae</li>
        </ul><ol><li>Vel exercitationem optio sed eaque quisquam in voluptatem dolorem sed voluptas voluptas est ratione tenetur. Sit veritatis error <a href="https://www.loremipzum.com" target="_blank">Cum ipsam et veritatis similique et sapiente velit</a>. At repudiandae nisi 33 galisum quia est voluptatem odit ut placeat omnis sit impedit voluptatem.</li>
        <li>Et veniam odit aut consequatur illum <a href="https://www.loremipzum.com" target="_blank">Aut reiciendis et adipisci laboriosam qui omnis culpa aut repudiandae sapiente</a>. Ut quae</li>
        </ol><p>&nbsp;</p>
variants:
  - name: default
    label: Single Select
    hidden: false
  - name: multi
    label: Multi Select
    hidden: true
    context:
      multiselectable: true
  - name: multiple
    label: Multiple accordion sets
    hidden: true
  - name: focus-test
    label: Accordion focus test
    hidden: true
