title: Blockquote
status: wip
order: 30
collated: false
meta:
  dependencies:
    stylesheets:
      - /components/background/background.css
context:
      blockquote_content: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
      blockquote_footer: Footer Details in Roboto
      blockquote_cite_url: https://uiowa.edu
      blockquote_cite_text: Link

variants:
  - name: default
    label: Left (default)
    hidden: false
    context:
      blockquote_class: blockquote
  - name: Center
    hidden: false
    context:
      blockquote_class: blockquote--center
  - name: Right
    hidden: false
    context:
      blockquote_class: blockquote--right
