title: Heading
order: 1
status: wip
hidden: false

variants:
  - name: default
    label: Headline
    hidden: false
    context:
        heading_level: h2
        heading_class:
        heading_url:
        heading_prefix: '$'
        heading: 'Bold Headline Here'
        heading_suffix: '%'
        heading_aria: test
  - name: Bold Headline Caps
    hidden: false
    context:
      heading_level: h2
      heading: Bold Headline
      heading_class: bold-headline bold-headline--caps
  - name: Bold Headline Serif
    hidden: false
    context:
      heading_level: h2
      heading: Bold Headline Serif
      heading_class: bold-headline bold-headline--serif


