title: Viewbook
label: Viewbook
hidden: false
order: 10
status: wip
meta:
  dependencies:
    stylesheets:
      - /components/branding/iowa-bar/iowa-bar.css
      - /components/branding/logo/logo.css
      - /components/branding/site-name/site-name.css
      - /components/branding/parent-site-name/parent-site-name.css
      - /components/branding/footer/footer.css
      - /components/typography/headings/headings.css
      - /components/typography/lists/lists.css
      - /components/tables/tables.css
      - /components/menus/top/top.css
      - /components/menus/main-menu/main-menu.css
      - /components/hero/hero.css
      - /components/headline/headline.css
      - /components/highlight/highlight.css
      - /components/button/button.css
      - /components/colors/colors.css
      - /components/aerial/aerial.css
      - /components/cta/cta.css
      - /components/card/card.css
      - /components/stat/stat.css
    scripts:
      - /components/branding/iowa-bar/iowa-bar.js
      - /components/menus/off-canvas/off-canvas.js
      - /components/card/card.js
context:
  site_name:
  site_slogan: College Name
  site_front: /
  site_title: Home Page
  header_alignment: site-header__default
  menu_type: superfish
  site_type: primary
  header_type: site-header--secondary
  nav_type: navbar--secondary
  iowa_bar_classes: 'iowa-bar--narrow'
  site_name_position: inline
  cta_title: 200+ Areas of Study
  cta_summary: Iowa offers over 200 majors, minors and certificates. Students are encouraged to work across disciplines to find their passion.
  cta_classes:
  cta_link_url: https://uiowa.edu/
  cta_link_title: Request Information
  cta_link_classes:
  row:
    items:
      - card_title: Business, economics, and management
        card_title_class: 'bold-headline bold-headline--caps bold-headline--highlight'
        card_link_title:
        card_link_url: https://admissions.uiowa.edu/academics/biz-econ-mgmt
        card_image: '../../assets/images/viewbook/areas/1.jpg'
        card_classes: card--overlay
        card_aria: desc-a-card
      - card_title: Education
        card_title_class: 'bold-headline bold-headline--caps bold-headline--highlight'
        card_link_title:
        card_link_url: https://admissions.uiowa.edu/academics/edu
        card_image: '../../assets/images/viewbook/areas/2.jpg'
        card_classes: card--overlay
        card_aria: desc-a-card
      - card_title: Engineering and computing
        card_title_class: 'bold-headline bold-headline--caps bold-headline--highlight'
        card_link_title:
        card_link_url: https://admissions.uiowa.edu/academics/engr-comp
        card_image: '../../assets/images/viewbook/areas/3.jpg'
        card_classes: card--overlay
        card_aria: desc-a-card
      - card_title: Health sciences
        card_title_class: 'bold-headline bold-headline--caps bold-headline--highlight'
        card_link_title:
        card_link_url: https://admissions.uiowa.edu/academics/health-sci
        card_image: '../../assets/images/viewbook/areas/4.jpg'
        card_classes: card--overlay
        card_aria: desc-a-card
      - card_title: Languages, culture, and society
        card_title_class: 'bold-headline bold-headline--caps bold-headline--highlight'
        card_link_title:
        card_link_url: https://admissions.uiowa.edu/academics/lang-cult-soc
        card_image: '../../assets/images/viewbook/areas/5.jpg'
        card_classes: card--overlay
        card_aria: desc-a-card
      - card_title: Life and natural sciences
        card_title_class: 'bold-headline bold-headline--caps bold-headline--highlight'
        card_link_title:
        card_link_url: https://admissions.uiowa.edu/academics/life-nat-sci
        card_image: '../../assets/images/viewbook/areas/6.jpg'
        card_classes: card--overlay
        card_aria: desc-a-card
      - card_title: Math and quantitative sciences
        card_title_class: 'bold-headline bold-headline--caps bold-headline--highlight'
        card_link_title:
        card_link_url: https://admissions.uiowa.edu/academics/math-quant-sci
        card_image: '../../assets/images/viewbook/areas/7.jpg'
        card_classes: card--overlay
        card_aria: desc-a-card
      - card_title: Preprofessional programs
        card_title_class: 'bold-headline bold-headline--caps bold-headline--highlight'
        card_link_title:
        card_link_url: https://admissions.uiowa.edu/academics/preprofessional
        card_image: '../../assets/images/viewbook/areas/8.jpg'
        card_classes: card--overlay
        card_aria: desc-a-card
      - card_title: Social sciences and policy
        card_title_class: 'bold-headline bold-headline--caps bold-headline--highlight'
        card_link_title:
        card_link_url: https://admissions.uiowa.edu/academics/soc-sci-pol
        card_image: '../../assets/images/viewbook/areas/9.jpg'
        card_classes: card--overlay
        card_aria: desc-a-card
      - card_title: Visual and performing arts
        card_title_class: 'bold-headline bold-headline--caps bold-headline--highlight'
        card_link_title:
        card_link_url: https://admissions.uiowa.edu/academics/vis-perf-arts
        card_image: '../../assets/images/viewbook/areas/10.jpg'
        card_classes: card--overlay
        card_aria: desc-a-card
      - card_title: Writing, communications, literature, and media
        card_title_class: 'bold-headline bold-headline--caps bold-headline--highlight'
        card_link_title:
        card_link_url: https://admissions.uiowa.edu/academics/write-comm-media
        card_image: '../../assets/images/viewbook/areas/11.jpg'
        card_classes: card--overlay
        card_aria: desc-a-card
      - card_title: Languages, culture, and society
        card_title_class: 'bold-headline bold-headline--caps bold-headline--highlight'
        card_link_title:
        card_link_url: https://admissions.uiowa.edu/academics/lang-cult-soc
        card_image: '../../assets/images/viewbook/areas/5.jpg'
        card_classes: card--overlay
        card_aria: desc-a-card
  link_bttn:
    items:
      - text: Apply Now
        url: https://uiowa.edu/
        item_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--apply
      - text:  Schedule a Visit
        url: https://uiowa.edu/
        item_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--visit
      - text: Ask Questions
        url: https://uiowa.edu/
        item_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--ask
      - text: Connect with Us
        url: https://uiowa.edu/
        item_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--connect
  stat_row_1:
    items:
      - stat_title: '34'
        stat_summary: 'u.s. news & world<br /> report'
        stat_content: 'Among the top 2% of universities worldwide.'
        stat_image: '../../images/examples/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: '#'
        stat_suffix:
        stat_classes: ''
      - stat_title: '15:1'
        stat_summary: 'STUDENT-TO-FACULTY<br /> RATIO'
        stat_content: 'Get to know your professors.'
        stat_image: '../../images/examples/stat-2.jpg'
        stat_image_position: 'bottom'
        stat_pattern:  '../../images/brain.png'
        stat_prefix:
        stat_suffix: ''
        stat_classes: ''
      - stat_title: '19'
        stat_summary: 'INTERNATIONAL FULBRIGHT<br />  SCHOLARS IN 2019'
        stat_content: 'That’s the same as some Ivy League schools.'
        stat_image: '../../images/examples/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: ''
        stat_suffix:
        stat_classes: ''
      - stat_title: '1 in 3'
        stat_summary: 'UNDERGRADS PARTICIPATE IN RESEARCH'
        stat_content: 'Gain experience now.'
        stat_image:
        stat_pattern:
        stat_prefix: ''
        stat_suffix:
        stat_classes: ''
  stat_row_2:
    items:
      - stat_title: '500'
        stat_summary: 'STUDENT<br />  ORGANIZATIONS'
        stat_content: 'Or, start your own'
        stat_image: '../../images/examples/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: ''
        stat_suffix: '+'
        stat_classes: ''
      - stat_title: '100'
        stat_summary: 'RESTAURANTS AND<br />  CAFÉS'
        stat_content: 'From vegan brunch to pie shakes.'
        stat_image: '../../images/examples/stat-2.jpg'
        stat_image_position: 'bottom'
        stat_pattern:  '../../images/brain.png'
        stat_prefix:
        stat_suffix: '+'
        stat_classes: ''
      - stat_title: '400'
        stat_summary: 'ARTS PERFORMANCES<br />  EACH YEAR'
        stat_content: 'For $5 or less.'
        stat_image: '../../images/examples/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: ''
        stat_suffix: '+'
        stat_classes: ''
      - stat_title: '24'
        stat_summary: 'NCAA DIVISION I<br />  TEAMS'
        stat_content: 'There’s nothing like a Hawkeye game.'
        stat_image:
        stat_pattern:
        stat_prefix: ''
        stat_suffix:
        stat_classes: ''
  stat_row_3:
    items:
      - stat_title: '95'
        stat_summary: 'OVERALL JOB/GRADUATE SCHOOL PLACEMENT RATE'
        stat_content: 'Business <strong>97%</strong><br />Education <strong>91%</strong><br />Engineering  <strong>96%</strong><br /> Liberal Arts and Sciences <strong>94%</strong><br /> Nursing <strong>99%</strong><br />Pharmacy <strong>97%</strong>'
        stat_image: '../../images/examples/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: ''
        stat_suffix: '%'
        stat_classes: ''
      - stat_title: '3,000'
        stat_summary: 'STUDENT<br />  INTERNSHIPS'
        stat_content: 'Everywhere from NASA to the Minnesota Vikings.'
        stat_image: '../../images/examples/stat-3.jpg'
        stat_image_position: 'top'
        stat_pattern: '../../images/brain.png'
        stat_prefix: ''
        stat_suffix: '+'
        stat_classes: ''
      - stat_title: '4,100'
        stat_summary: 'IOWA GRADUATES<br />  Hired'
        stat_content: 'In the past three years.  Gain real-world skills that make résumés stand out.'
        stat_image:
        stat_pattern:
        stat_prefix: ''
        stat_suffix: '+'
        stat_classes: ''
      - stat_title: '1,316'
        stat_summary: 'STUDENTS STUDIED ABROAD LAST YEAR'
        stat_content: 'Spanning the globe in 69 countries.'
        stat_image: '../../images/examples/stat-2.jpg'
        stat_image_position: 'bottom'
        stat_pattern:  '../../images/brain.png'
        stat_prefix:
        stat_suffix: '+'
        stat_classes: ''
  button:
    text: Call to Action
    link: https://example2.com
    type: bttn--basic bttn--tertiary
variants:
  - name: default
    label: Default Secondary Superfish

