title: Viewbook
label: Viewbook
hidden: false
order: 10
status: wip
meta:
  dependencies:
    stylesheets:
      - /components/branding/iowa-bar/iowa-bar.css
      - /components/branding/logo/logo.css
      - /components/branding/site-name/site-name.css
      - /components/branding/parent-site-name/parent-site-name.css
      - /components/branding/footer/footer.css
      - /components/typography/headings/headings.css
      - /components/typography/lists/lists.css
      - /components/menus/top/top.css
      - /components/menus/main-menu/main-menu.css
      - /components/hero/hero.css
      - /components/headline/headline.css
      - /components/highlight/highlight.css
      - /components/button/button.css
      - /components/colors/colors.css
      - /components/aerial/aerial.css
    scripts:
      - /components/branding/iowa-bar/iowa-bar.js
      - /components/menus/off-canvas/off-canvas.js
context:
  site_name: Department of College
  site_slogan: College Name
  site_front: /
  site_title: Home Page
  header_alignment: site-header__default
  menu_type: superfish
  site_type: primary
  header_type: site-header--secondary
  nav_type: navbar--secondary
  link_bttn:
    items:
      - text: Apply
        url: https://uiowa.edu/
        item_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--apply
      - text:  Visit
        url: https://uiowa.edu/
        item_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--visit
      - text: Request Info
        url: https://uiowa.edu/
        item_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--request
      - text: Jobs
        url: https://uiowa.edu/
        item_class: bttn bttn--outline bttn--tertiary bttn--transparent bttn--caps bttn--jobs
  button:
    text: Call to Action
    link: https://example2.com
    type: bttn--basic bttn--tertiary
variants:
  - name: default
    label: Default Secondary Superfish

