title: Aerial Block
name: Aerial
order: 99
status: wip
collate: false
meta:
  dependencies:
    stylesheets:
      - /components/headline/headline.css
      - /components/highlight/highlight.css
      - /components/button/button.css
      - /components/colors/colors.css
variants:
  - name: default
    hidden: false
    context:
      aerial_title: 'Welcome Home'
      aerial_image: '../../assets/images/viewbook/sections/12.jpg'
      grid_title_1: 'World-class hospital'
      grid_sub_1: 'The University of Iowa is home to the best comprehensive medical center in Iowa–and one of the best in the country'
      grid_title_2: 'A real college town'
      grid_sub_2: 'Most college towns are just towns near a college. Not Iowa City. The campus and downtown are woven into each other'
      grid_title_3: 'Easy to get around'
      grid_sub_3: 'Big schools have to be big, right?  Nope. Everything on campus is within walking distance, with free buses to get you there faster'
      grid_title_4: 'Big ten athletics'
      grid_sub_4: 'Kinnick Stadium, with its 69,000+ seats, is the home of Hawkeye Football. But on gameday, the entire town turns black and gold'
