title: Hero
order: 0
status: wip
hidden: false
collate: false
meta:
  dependencies:
    stylesheets:
      - /components/headline/headline.css
      - /components/button/button.css
      - /components/colors/colors.css
context:
  hero_type: image
  hero_size: medium
  hero_content: center
  hero_title: 'We’re in this together'
  hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you can do—to make your return to campus safer.</p><p><a class="bttn bttn--primary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
  hero_overlay: gradient-center
  hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
  hero_classes: bg--black
variants:
  - name: default
    label: Centered Default
    hidden: false
  - name: Centered Highlighted
    label: Centered Highlighted
    notes: This version uses a headline with a gold background highlight with the button using a secondary color scheme.
    context:
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you can do—to make your return to campus safer.</p><p><a class="bttn bttn--secondary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
  - name: lower_left
    label: Lower Left Default
    notes: This version can also be used for the page title hero variant and uses a vertical gradient that doesn't extend as far as the default centered gradient.
    context:
      hero_content: bottom
      hero_title: 'We’re in this together'
      hero_overlay: gradient-center-left
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you can do—to make your return to campus safer.</p><p><a class="bttn bttn--primary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
  - name: lower_left_highlighted
    label: Lower Left Highlighted
    notes: This version uses a headline with a gold background highlight with the button using a secondary color scheme.
    context:
      hero_content: bottom
      hero_title: 'We’re in this together'
      hero_overlay: gradient-center-left
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you can do—to make your return to campus safer.</p><p><a class="bttn bttn--secondary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
  - name: banner
    label: Banner Default
    notes: The banner variant has a smaller vertical height, smaller heading size, and lighter paragraph font weight. This version uses a horizontal left gradient.  The content is vertically centered and left aligned.
    context:
      hero_content: 'bottom hero--banner'
      hero_title: 'We’re in this together'
      hero_overlay: gradient-left
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you can do—to make your return to campus safer.</p><p><a class="bttn bttn--primary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
  - name: banner_bg_color
    label: Banner w/ Background Pattern
    notes: The banner variant has a smaller vertical height, smaller heading size, and lighter paragraph font weight. This version uses a horizontal left gradient.  The content is vertically centered and left aligned.
    context:
      hero_content: 'bottom hero--banner'
      hero_type:
      hero_title: 'We’re in this together'
      hero_overlay: solid-opacity
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you can do—to make your return to campus safer.</p><p><a class="bttn bttn--primary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
      hero_classes: bg-pattern--brain-black
  - name: banner_bg_color_reversed
    label: Banner w/ Background Pattern Reversed
    notes: The banner variant has a smaller vertical height, smaller heading size, and lighter paragraph font weight. This version uses a horizontal left gradient.  The content is vertically centered and left aligned.
    context:
      hero_content: 'bottom hero--banner'
      hero_type:
      hero_title: 'We’re in this together'
      hero_overlay:
      hero_title_classes: 'bold-headline--serif bold-headline'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you can do—to make your return to campus safer.</p><p><a class="bttn bttn--primary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
      hero_classes: bg-pattern--brain
  - name: banner_centered
    label: Banner Default Centered
    notes: The banner variant has a smaller vertical height, smaller heading size, and lighter paragraph font weight. This version uses a solid black opacity.  The content is vertically and horizontally centered.
    context:
      hero_content: 'center hero--banner'
      hero_title: 'We’re in this together'
      hero_overlay: solid-opacity
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.</p><p><a class="bttn bttn--primary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
  - name: banner_thin
    label: Banner Thin Default
    notes: This version of the banner has a very thin height and is meant for a very small amount of text.
    context:
      hero_size: thin
      hero_content: 'bottom hero--banner'
      hero_title: 'We’re in this together'
      hero_overlay: gradient-left
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.</p><p><a class="bttn bttn--primary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
  - name: banner_thin_centered
    label: Banner Thin Centered
    notes: This is a version of the thin banner that is centered with a solid black opacity
    context:
      hero_size: thin
      hero_content: 'center hero--banner'
      hero_title: 'We’re in this together'
      hero_overlay: solid-opacity
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.</p><p><a class="bttn bttn--primary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
  - name: banner_thin_centered_bg_color
    label: Banner Thin Centered w/ Pattern
    notes: This is a version of the thin banner that is centered with a solid black opacity
    context:
      hero_size: thin
      hero_type:
      hero_content: 'center hero--banner'
      hero_title: 'We’re in this together'
      hero_overlay: solid-opacity
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.</p><p><a class="bttn bttn--secondary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
      hero_classes: bg-pattern--brain-black
  - name: banner_thin_centered_bg_color_reversed
    label: Banner Thin Centered w/ Pattern Reversed
    notes: This is a version of the thin banner that is centered with a solid black opacity
    context:
      hero_size: thin
      hero_type:
      hero_content: 'center hero--banner'
      hero_title: 'We’re in this together'
      hero_overlay:
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.</p><p><a class="bttn bttn--secondary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
      hero_classes: bg-pattern--brain
  - name: video
    label: Video
    hidden: false
    notes: The Hero video variant is vertically centered with a play/pause button positioned in the lower left-hand corner.
    context:
      hero_type: video
      hero_content: center
      hero_overlay: solid-opacity
      hero_title: 'We’re in this together'
      hero_image: ../../images/hero-image.jpg
      hero_image_alt: 'View of University of Iowa Campus'
      hero_video: '../../assets/video/home.mp4'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you can do—to make your return to campus safer.</p><p><a class="bttn bttn--primary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'

