title: Hero
order: 0
status: wip
hidden: false
collate: false
meta:
  dependencies:
    stylesheets:
      - /components/headline/headline.css
      - /components/button/button.css
context:
  hero_type: image
  hero_content: center
  hero_title: 'See for yourself'
  hero_text: '<p>Iowa is where great stories begin and It is time to start yours - find out how</p>'
  hero_overlay: solid
  hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
variants:
  - name: default
    label: Centered
    hidden: false
  - name: Left
    label: Left
    context:
      hero_type: image
      hero_content: bottom
      hero_title: 'The Steps Forward'
      hero_overlay: gradient
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      hero_text: '<p class="element--light-intro">Returning to Campus - <strong>Fall 2020</strong></p>'
  - name: Video
    context:
      hero_type: video
      hero_content: center
      hero_title: 'See for yourself'
      hero_image: ../../images/hero-image.jpg
      hero_image_alt: 'View of University of Iowa Campus'
      hero_video: '../../assets/video/home.mp4'
      hero_text: '<p>Iowa is where great stories begin and It is time to start yours - find out how</p>'

