title: Hero
order: 0
hidden: false
collate: false
meta:
  dependencies:
    stylesheets:
      - /components/headline/headline.css
      - /components/button/button.css
context:
  hero_type: image
  hero_content: center
  hero_title: 'See for yourself'
  hero_text: '<p>See for yourself where you will graduate in a few years</p>'
  hero_overlay: solid
  hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
variants:
  - name: default
    label: Centered
    hidden: false
  - name: Left
    label: Left
    context:
      hero_type: image
      hero_content: bottom
      hero_title: 'Very Long Headline that Could Possibly Span Multiple Lines'
      hero_overlay: gradient
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
  - name: Video
    context:
      hero_type: video
      hero_content: center
      hero_title: 'See for yourself'
      hero_image: ../../images/hero-image.jpg
      hero_image_alt: 'View of University of Iowa Campus'
      hero_video: '../../assets/video/home.mp4'

