title: Hero
order: 0
status: wip
hidden: false
collate: false
meta:
  dependencies:
    stylesheets:
      - /components/headline/headline.css
      - /components/button/button.css
context:
  hero_type: image
  hero_content: center
  hero_title: 'We’re in this together'
  hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you an do—to make your return to campus safer.</p><p><a class="bttn bttn--primary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
  hero_overlay: solid
  hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
variants:
  - name: default
    label: Centered Default
    hidden: false
  - name: Centered Highlighted
    label: Centered Highlighted
    context:
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you an do—to make your return to campus safer.</p><p><a class="bttn bttn--secondary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
  - name: Left Default
    label: Left Default
    context:
      hero_type: image
      hero_content: bottom
      hero_title: 'We’re in this together'
      hero_overlay: gradient
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--negative'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you an do—to make your return to campus safer.</p><p><a class="bttn bttn--primary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'
  - name: Left Highlighted
    label: Left Highlighted
    context:
      hero_type: image
      hero_content: bottom
      hero_title: 'We’re in this together'
      hero_overlay: gradient
      hero_title_classes: 'bold-headline--serif bold-headline bold-headline--highlight'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you an do—to make your return to campus safer.</p><p><a class="bttn bttn--secondary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'

  - name: Video
    hidden: true
    context:
      hero_type: video
      hero_content: center
      hero_overlay: gradient
      hero_title: 'We’re in this together'
      hero_image: ../../images/hero-image.jpg
      hero_image_alt: 'View of University of Iowa Campus'
      hero_video: '../../assets/video/home.mp4'
      hero_text: '<p>Every Hawkeye has a role to play in preventing the spread of COVID-19.<br />
Find out what Iowa’s doing—and what you an do—to make your return to campus safer.</p><p><a class="bttn bttn--primary bttn--caps" href="/student-life/iowa-city">Read Fall 2020 guidelines <span class="fa-arrow-right fas"></span> </a></p>'

