title: Main Menu
hidden: false
order: 4
status: wip
meta:
  dependencies:
    stylesheets:
      - /components/typography/headings/headings.css
      - /components/banner/banner.css
      - /components/headline/headline.css
      - /components/button/button.css
      - /components/background/background.css
      - /components/typography/lists/lists.css
context:
    field_title: Headline
    menu_type: main
    site_type: primary
    links_nav:
      title: Additional Navigation
      title_classes: element-invisible
variants:
  - name: default
    hidden: false
    context:
      nav_type: menu-wrapper
      links_nav:
        links:
          - link_nav_text: Admissions
            link_nav_classes: item--first
          - link_nav_text: Academics
            link_nav_classes: menuparent--active is-active
            links:
              - link_nav_text: Undergraduate
                link_nav_classes:
              - link_nav_text: Graduate
                link_nav_classes:
              - link_nav_text: International
                link_nav_classes:
              - link_nav_text: Distance and online
                link_nav_classes:
              - link_nav_text: Cost and aid
                link_nav_classes:
          - link_nav_text: Research
            link_nav_classes:
          - link_nav_text: About
            link_nav_classes:
  - name: Main Menu Secondary Horizontal - Gray Background
    hidden: true
    context:
      nav_type: menu-wrapper menu-wrapper--horizontal
      menu_bg: bg--gray
      links_nav:
        links:
          - link_nav_text: Admissions
            link_nav_classes: item--first
          - link_nav_text: Academics
            link_nav_classes: menuparent--active is-active
            links:
              - link_nav_text: Undergraduate
                link_nav_classes:
              - link_nav_text: Graduate
                link_nav_classes:
              - link_nav_text: International
                link_nav_classes:
              - link_nav_text: Distance and online
                link_nav_classes:
              - link_nav_text: Cost and aid
                link_nav_classes:
          - link_nav_text: Research
            link_nav_classes:
          - link_nav_text: About
            link_nav_classes:
  - name: Main Menu Sidebar
    hidden: true
    context:
      nav_type: menu-wrapper menu-wrapper--vertical
      links_nav:
        links:
        - link_nav_text: Admissions
          link_nav_classes: item--first
        - link_nav_text: Academics
          link_nav_classes: menuparent--active is-active
          links:
          - link_nav_text: Undergraduate
            link_nav_classes:
          - link_nav_text: Graduate
            link_nav_classes:
          - link_nav_text: International
            link_nav_classes:
          - link_nav_text: Distance and online
            link_nav_classes:
          - link_nav_text: Cost and aid
            link_nav_classes:
        - link_nav_text: Research
          link_nav_classes:
        - link_nav_text: About
          link_nav_classes:
  - name: links
    label: Links
    hidden: true
