title: Basic Page
label: Basic Page
hidden: false
order: 10
status: wip
meta:
  dependencies:
    stylesheets:
      - /components/branding/iowa-bar/iowa-bar.css
      - /components/branding/logo/logo.css
      - /components/branding/site-name/site-name.css
      - /components/branding/parent-site-name/parent-site-name.css
      - /components/branding/footer/footer.css
      - /components/typography/headings/headings.css
      - /components/typography/lists/lists.css
      - /components/menus/off-canvas/off-canvas.css
    scripts:
      - /components/branding/iowa-bar/iowa-bar.js
      - /components/menus/off-canvas/off-canvas.js
context:
  site_name: Department of College
  site_slogan: College Name
  site_front: /
  site_title: Home Page
  header_alignment: site-header__default
  menu_type: superfish
  site_type: primary
  header_type: site-header--secondary
  nav_type: navbar--secondary
  button:
    text: Call to Action
    link: https://example2.com
    type: bttn--basic bttn--tertiary
variants:
  - name: default
    label: Default Secondary Superfish
