name: image
label: Image
hidden: true
context:
  image_sizes: (min-width:1310px) 1310px, 100vw
  image_srcs:
    - path: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/bg-image.jpg
      size: 384w
    - path: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/bg-image.jpg
      size: 768w
    - path: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/bg-image.jpg
      size: 1024w
    - path: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/bg-image.jpg
      size: 1312w
    - path: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/bg-image.jpg
      size: 1920w
    - path: https://sandbox.prod.drupal.uiowa.edu/sites/sandbox.uiowa.edu/files/2021-03/bg-image.jpg
      size: 2592w
