name: image
label: Image
hidden: true
context:
  image_sizes: (min-width:1310px) 1310px, 100vw
  image_srcs:
    - path: ../../assets/images/drone.jpg
      size: 384w
    - path: ../../assets/images/drone.jpg
      size: 768w
    - path: ../../assets/images/drone.jpg
      size: 1024w
    - path: ../../assets/images/drone.jpg
      size: 1312w
    - path: ../../assets/images/drone.jpg
      size: 1920w
    - path: ../../assets/images/drone.jpg
      size: 2592w
