hidden: true
status: prototype
meta:
  dependencies:
    stylesheets:
      - /components/typography/headings/headings.css
      - /components/headline/headline.css
      - /components/button/button.css
      - /components/card/card.css
      - /components/blockquote/blockquote.css
      - /components/media/media.css
      - /components/background/background.css
      - /components/colors/colors.css
context:
  backgrounds: '@background.backgrounds'
  headlines: '@headline.headlines'
  cards:
    - card_title: Dedicated to having an impact on human health
      card_classes: card--stacked bg--white
      card_link_title: View Story
      card_link_url: https://uiowa.edu/
      card_image: '../../assets/images/examples/feature1.jpg'
      card_content: <p>Molecular <a href="https://hr.uiowa.edu">medicine PhD</a> student Jordan Kohlmeyer is researching new therapies for malignant peripheral nerve sheath tumors, which are deadly, resistant to drug therapies, and often unable to be operated upon due to their location.</p>
      card_date: June 14, 1984
      card_subtitle: By Lee Hermiston
      card_aria: desc-a-card
    - card_title: Swinging for the fences in sports management
      card_link_title: View Story
      card_link_url: https://uiowa.edu/
      card_image: '../../assets/images/examples/feature4.jpg'
      card_content: <p>Jake Stone is heading to the Baltimore Orioles organization after graduation. He says this was made possible by taking advantage of the opportunities offered by the University of Iowa’s Sport and Recreation Management Program and his work with the Hawkeye baseball team.</p>
      card_date: June 14, 1984
      card_subtitle: By Lee Hermiston
      card_classes: card--enclosed card--stacked
      card_aria: desc-a-card
    - card_title: Turning the tide for sick seals
      card_link_title: View Story
      card_link_url: https://uiowa.edu/
      card_image: '../../assets/images/examples/feature3.jpg'
      card_content: <p>As the attending veterinarian at a marine mammal hospital in Los Angeles, University of Iowa alumna Lauren Palmer aims to rehabilitate and release sick or injured animals—and to help educate people about the ocean’s ecosystem.</p>
      card_date: June 14, 1984
      card_subtitle: By Sara Epstein Moninger
      card_classes: 'bg--gold card--stacked'
      card_aria: desc-a-card
  horizontal_cards:
    - card_title: Getting to know Iowa's fall 2018 graduates
      card_image: '../../assets/images/events-01.jpg'
      card_image_classes: 'media--border media--circle'
      card_classes: 'bg--white card--media-left'
      card_content: <p>Applications can be submitted via Iowa’s web application portal, the Common Application, and Coalition App. Once submitted, <a href="/">you</a> can track the status of your application through MyUI, a one-stop resource for current and prospective Iowa students.</p>
      card_date: June 14, 1984
      card_tag: Carver-Hawkeye Arena
      card_subtitle: Card Subtitle
      card_link_url: https://uiowa.edu/
      card_link_title: View Story
      card_media_classes: 'media--circle card__media--small'
    - card_title: Getting to know Iowa's fall 2018 graduates
      card_image: '../../assets/images/events-01.jpg'
      card_image_classes: 'media--border media--circle'
      card_classes: 'bg--black card--media-left'
      card_content: <p>Applications can be submitted via Iowa’s web application portal, the Common Application, and Coalition App. Once submitted, <a href="/">you</a> can track the status of your application through MyUI, a one-stop resource for current and prospective Iowa students.</p>
      card_date: June 14, 1984
      card_tag: Carver-Hawkeye Arena
      card_subtitle: Card Subtitle
      card_link_url: https://uiowa.edu/
      card_link_title: View Story
      card_media_classes: 'media--circle card__media--small'
    - card_title: Getting to know Iowa's fall 2018 graduates
      card_image: '../../assets/images/events-01.jpg'
      card_image_classes: 'media--border media--circle'
      card_classes: 'bg--gray card--media-left'
      card_content: <p>Iowa's leader<em>ship in both t</em>he arts <sub>and scien</sub>ces fosters unique resou<u>rces, like the </u>Coll<a data-entity-substitution="canonical" data-entity-type="node" data-entity-uuid="59f8f236-7301-4dcb-afc6-3d535ae6fc6b" href="/node/21" media_library="Media Library">ege of Medi</a>cine's Arts and Humanities Program, that will help <strong>you stand out.</strong></p><blockquote><p>Blockquote Text</p></blockquote><h2>Heading 2</h2><h3>Heading 3</h3><h4>Heading 4</h4><h6>Heading 6</h6>
      card_date: June 14, 1984
      card_tag: Carver-Hawkeye Arena
      card_subtitle: Card Subtitle
      card_link_url: https://uiowa.edu/
      card_link_title: View Story
      card_media_classes: 'media--circle card__media--small'

