title: Alerts
status: wip
order: 1
collated: false
variants:
  - name: default
    label: Hawk Alert
    status: null
    context:
      alert_level: alert-danger
      alert_icon:
      alert_heading: Hawk Alert
      alert_date: 03-01-2020 7:35 am
      alert_text: 'Test Hawk Alert: This is a test of the Hawk Alert system conducted by Cindy Schooley. This is only a test.'
      alert_link_text: Visit e.uiowa.edu for more information.
      alert_link: https://e.uiowa.edu
  - name: Success
    context:
      alert_level: alert-success
      alert_icon: <i class="fas fa-check-circle"></i>
      alert_heading:
      alert_date:
      alert_text: '<strong>Success:</strong> there are no active alerts at this time.&nbsp;'
      alert_link_text: Visit e.uiowa.edu for more information.
      alert_link: https://e.uiowa.edu
  - name: Warning
    context:
      alert_level: alert-warning
      alert_icon: <i class="fas fa-exclamation-circle"></i>
      alert_heading:
      alert_date:
      alert_text: '<strong>Warning:</strong> there are active alerts at this time.&nbsp;'
      alert_link_text: Visit e.uiowa.edu for more information.
      alert_link: https://e.uiowa.edu
  - name: Info
    context:
      alert_level: alert-info
      alert_icon: <i class="fas fa-info-circle"></i>
      alert_heading:
      alert_date:
      alert_text: '<strong>Info:</strong> there are no active alerts at this time.&nbsp;'
      alert_link_text: Visit e.uiowa.edu for more information.
      alert_link: https://e.uiowa.edu
  - name: Danger
    context:
      alert_level: alert-danger
      alert_icon: <i class="fas fa-exclamation-circle"></i>
      alert_heading:
      alert_date:
      alert_text: '<strong>Danger:</strong> there are active alerts at this time.&nbsp;'
      alert_link_text: Visit e.uiowa.edu for more information.
      alert_link: https://e.uiowa.edu
  - name: System Message
    context:
      alert_level: alert-dismissible alert-success
      alert_icon: <i class="fas fa-times-circle"></i>
      alert_heading:
      alert_date:
      alert_text: 'Basic page <em class="placeholder"><a href="/student-life" hreflang="en">Student life</a></em> has been updated.'
      alert_link_text:
      alert_link:
