name: Tests

on:
  pull_request:
    branches:
      - 4.x

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Enable corepack
        run: |
          corepack enable
          corepack prepare yarn@3.7.0 --activate
          yarn set version 3.7.0

      - name: Install dependencies
        run: yarn install --immutable

      - name: Test unit
        run: yarn run test:unit
