name: Tests

# Runs the unit suite.

on:
  push:
    branches:
      - 5.x
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Enable corepack
        run: |
          corepack enable
          corepack prepare yarn@3.7.0 --activate
          yarn set version 3.7.0

      - run: yarn install --immutable

      - name: Test unit suite
        run: yarn test:unit --run
