hidden: false
status: prototype
order: 0
meta:
  dependencies:
    stylesheets:
#      - /components/button/button.css
      - /components/headline/headline.css
context:
  backgrounds:
    - bg_name: Black
      bg_class: 'bg--black'
    - bg_name: 'Black - Brain pattern'
      bg_class: 'bg--black--pattern--brain'
    - bg_name: Gold
      bg_class: 'bg--gold'
    - bg_name: 'Gold - Brain pattern'
      bg_class: 'bg--gold--pattern--brain'
    - bg_name: Gray
      bg_class: 'bg--gray'
    - bg_name: White
      bg_class: 'bg--white'
    - bg_name: 'White - Brain pattern'
      bg_class: 'bg--white--pattern--brain'
