label: Header
name: header
hidden: true
context:
  site_name_position: inline
  parent_site:
    name: ''
    url: ''
variants:
  - name: default
    label: With toggle navigation
  - name: site_name_below
    label: Site name below
    context:
      site_name_position: below
  - name: parent_site
    label: With parent site
    context:
      parent_site:
        name: Graduate College
        url: 'https://grad.uiowa.edu'
